In [1]:
import pandas as pd
import glob
import os

##### List all the CSV file

In [2]:
files = [f for f in glob.glob("*.csv") if f != "sales_cleaned_final.csv"]

##### Combine all the CSV file

In [3]:
# Only 1 header
df = pd.concat([pd.read_csv(f, header=0) for f in files], ignore_index=True)

# Remove rows where all columns are identical to the column headers
df = df[~(df == df.columns).all(axis=1)]

df

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001"
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016"
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016"
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016"
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016"

##### Check if there are blank rows

In [4]:
blank_rows = df[df.isna().all(axis=1)]
blank_rows

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
1,NaN,NaN,NaN,NaN,NaN,NaN
356,NaN,NaN,NaN,NaN,NaN,NaN
735,NaN,NaN,NaN,NaN,NaN,NaN
1433,NaN,NaN,NaN,NaN,NaN,NaN
1553,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
185176,NaN,NaN,NaN,NaN,NaN,NaN
185438,NaN,NaN,NaN,NaN,NaN,NaN
186042,NaN,NaN,NaN,NaN,NaN,NaN
186548,NaN,NaN,NaN,NaN,NaN,NaN
186826,NaN,NaN,NaN,NaN,NaN,NaN

##### Delete all blank rows

In [5]:
df = df.dropna(how='all')
df

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001"
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016"
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016"
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016"
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016"

##### Rename column header

In [6]:
df.columns = ['order_id', 'product', 'quantity_ordered', 'price_each', 'order_datetime', 'purchase_address']
df.head()

,order_id,product,quantity_ordered,price_each,order_datetime,purchase_address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"

##### Check duplicates by order_id

In [7]:
duplicates = df[df.duplicated(subset=['order_id'])]
duplicates

,order_id,product,quantity_ordered,price_each,order_datetime,purchase_address
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
19,176574,USB-C Charging Cable,1,11.95,04/03/19 19:42,"20 Hill St, Los Angeles, CA 90001"
31,176585,Bose SoundSport Headphones,1,99.99,04/07/19 11:31,"823 Highland St, Boston, MA 02215"
33,176586,Google Phone,1,600,04/10/19 17:00,"365 Center St, San Francisco, CA 94016"
120,176672,USB-C Charging Cable,1,11.95,04/12/19 11:07,"778 Maple St, New York City, NY 10001"
...,...,...,...,...,...,...
186784,259297,Lightning Charging Cable,1,14.95,09/15/19 18:54,"138 Main St, Boston, MA 02215"
186785,259297,Lightning Charging Cable,1,14.95,09/15/19 18:54,"138 Main St, Boston, MA 02215"
186792,259303,AA Batteries (4-pack),1,3.84,09/20/19 20:18,"106 7th St, Atlanta, GA 30301"
186804,259314,AAA Batteries (4-pack),2,2.99,09/16/19 00:25,"241 Highland St, Atlanta, GA 30301"
186842,259350,USB-C Charging Cable,1,11.95,09/30/19 13:49,"519 Maple St, San Francisco, CA 94016"

##### Delete duplicates by order_id

In [8]:
df = df.drop_duplicates(subset=['order_id'], keep='first')
df

,order_id,product,quantity_ordered,price_each,order_datetime,purchase_address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
6,176562,USB-C Charging Cable,1,11.95,04/29/19 13:03,"381 Wilson St, San Francisco, CA 94016"
...,...,...,...,...,...,...
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001"
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016"
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016"
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016"
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016"

##### Reset Index

In [9]:
df = df.reset_index(drop=True)
df.head()

,order_id,product,quantity_ordered,price_each,order_datetime,purchase_address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
2,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
3,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
4,176562,USB-C Charging Cable,1,11.95,04/29/19 13:03,"381 Wilson St, San Francisco, CA 94016"

##### Rename the 'index' column into 'No.'

In [10]:
df.rename(columns={'index': 'No.'}, inplace=True)
df.head()

,order_id,product,quantity_ordered,price_each,order_datetime,purchase_address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
2,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
3,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
4,176562,USB-C Charging Cable,1,11.95,04/29/19 13:03,"381 Wilson St, San Francisco, CA 94016"

##### Separate date and time

In [11]:
# Format date and time into the same format
df['order_datetime'] = pd.to_datetime(df['order_datetime'], format='%m/%d/%y %H:%M', errors='coerce')

# Separate date -> yyyy-mm-dd
df['order_date'] = df['order_datetime'].dt.date

# Separate month -> just the month
df['order_month'] = df['order_datetime'].dt.month

# Add quarter
df['order_quarter'] = pd.cut(
    df['order_month'], 
    bins=[0, 3, 6, 9, 12],
    labels=['Q1', 'Q2', 'Q3', 'Q4']
)

# Separate time
df['order_time'] = df['order_datetime'].dt.strftime('%H:%M')

# Delete the 'order_datetime' column
df.drop('order_datetime', axis=1, inplace=True)

# Check the table
df

,order_id,product,quantity_ordered,price_each,purchase_address,order_date,order_month,order_quarter,order_time
0,176558,USB-C Charging Cable,2,11.95,"917 1st St, Dallas, TX 75001",2019-04-19,4,Q2,08:46
1,176559,Bose SoundSport Headphones,1,99.99,"682 Chestnut St, Boston, MA 02215",2019-04-07,4,Q2,22:30
2,176560,Google Phone,1,600,"669 Spruce St, Los Angeles, CA 90001",2019-04-12,4,Q2,14:38
3,176561,Wired Headphones,1,11.99,"333 8th St, Los Angeles, CA 90001",2019-04-30,4,Q2,09:27
4,176562,USB-C Charging Cable,1,11.95,"381 Wilson St, San Francisco, CA 94016",2019-04-29,4,Q2,13:03
...,...,...,...,...,...,...,...,...,...
178432,259353,AAA Batteries (4-pack),3,2.99,"840 Highland St, Los Angeles, CA 90001",2019-09-17,9,Q3,20:56
178433,259354,iPhone,1,700,"216 Dogwood St, San Francisco, CA 94016",2019-09-01,9,Q3,16:00
178434,259355,iPhone,1,700,"220 12th St, San Francisco, CA 94016",2019-09-23,9,Q3,07:39
178435,259356,34in Ultrawide Monitor,1,379.99,"511 Forest St, San Francisco, CA 94016",2019-09-19,9,Q3,17:30
178436,259357,USB-C Charging Cable,1,11.95,"250 Meadow St, San Francisco, CA 94016",2019-09-30,9,Q3,00:18

##### Separate address into street, city, state, zip

In [12]:
# Separate street, city, state_zip
df[['street', 'city', 'state_zip']] = df['purchase_address'].str.split(',', expand=True)

# Separate state and zip from 'state_zip' column
df[['state','zip']] = df['state_zip'].str.strip().str.split(' ', n=1, expand=True)

# Delete the 'purchase_address' and 'state_zip' column
df.drop(['purchase_address','state_zip'], axis=1, inplace=True)

# Check the table
df

,order_id,product,quantity_ordered,price_each,order_date,order_month,order_quarter,order_time,street,city,state,zip
0,176558,USB-C Charging Cable,2,11.95,2019-04-19,4,Q2,08:46,917 1st St,Dallas,TX,75001
1,176559,Bose SoundSport Headphones,1,99.99,2019-04-07,4,Q2,22:30,682 Chestnut St,Boston,MA,02215
2,176560,Google Phone,1,600,2019-04-12,4,Q2,14:38,669 Spruce St,Los Angeles,CA,90001
3,176561,Wired Headphones,1,11.99,2019-04-30,4,Q2,09:27,333 8th St,Los Angeles,CA,90001
4,176562,USB-C Charging Cable,1,11.95,2019-04-29,4,Q2,13:03,381 Wilson St,San Francisco,CA,94016
...,...,...,...,...,...,...,...,...,...,...,...,...
178432,259353,AAA Batteries (4-pack),3,2.99,2019-09-17,9,Q3,20:56,840 Highland St,Los Angeles,CA,90001
178433,259354,iPhone,1,700,2019-09-01,9,Q3,16:00,216 Dogwood St,San Francisco,CA,94016
178434,259355,iPhone,1,700,2019-09-23,9,Q3,07:39,220 12th St,San Francisco,CA,94016
178435,259356,34in Ultrawide Monitor,1,379.99,2019-09-19,9,Q3,17:30,511 Forest St,San Francisco,CA,94016
178436,259357,USB-C Charging Cable,1,11.95,2019-09-30,9,Q3,00:18,250 Meadow St,San Francisco,CA,94016

##### Save the final CSV:

In [18]:
from IPython.display import FileLink

df.to_csv("sales_cleaned_final.csv", index=False)

display(FileLink("sales_cleaned_final.csv"))

OSError: [Errno 9] Bad file descriptor